[package]
name = "osmflatc"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
description = "OpenStreetMap (OSM) data converter from PBF format to osmflat format"
repository = "https://github.com/boxdot/osmflat-rs"
keywords = ["serialization", "osm", "openstreetmap", "flatdata"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"

[dependencies]
byteorder = "1.3.2"
bytes = "0.4.12"
colored = "1.8.0"
crossbeam = "0.7.2"
env_logger = "0.6.2"
flatdata = "0.3.1"
flate2 = "1.0.11"
inlinable_string = "0.1.10"
itertools = "0.8.0"
log = "0.4.8"
memmap = "0.7.0"
osmflat = "0.1.0"
parking_lot = "0.9.0"
pbr = "1.0.1"
prost = "0.5.0"
prost-derive = "0.5.0"
prost-types = "0.5.0"
rayon = "1.2.0"
structopt = "0.3.1"

[build-dependencies]
prost-build = "0.5.0"

[dev-dependencies]
proptest = "0.9.4"
