[package]
name = "osmflat"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
description = "Flat OpenStreetMap (OSM) data format providing an efficient random data access through memory mapped files."
repository = "https://github.com/boxdot/osmflat-rs"
keywords = ["serialization", "osm", "openstreetmap", "flatdata"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"

[dependencies]
flatdata = "0.3.1"

[dev-dependencies]
itertools = "0.8.0"
png = "0.15.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
smallvec = "0.6.10"
structopt = "0.3.1"
svg = "0.6.0"
